"""Research execution application layer.

This module provides services for executing research queries generated by
the preflight system across multiple research databases and web search.
"""

from .services import ResearchQueryExecutor, QueryExecutionResult

__all__ = ['ResearchQueryExecutor', 'QueryExecutionResult']
